{...}:
{
  imports =
  [
    ./apps/fastFetch.nix
    ./apps/librewolf.nix
    ./apps/kitty.nix
    ./compositors/hyprland.nix
    ./compositorTools/hyprlock.nix
    ./compositorTools/hyprpaper.nix
    ./compositorTools/hyprTweaks.nix
    ./compositorTools/hyprWorkspaceStart.nix
    ./compositorTools/dunst.nix
    ./compositorTools/waybar.nix
    ./compositorTools/wofiPowerMenu.nix
    ./customOptions/desktopStyleOptions.nix
    ./customOptions/desktopSystemOptions.nix
    ./customOptions/themingOptions.nix
    ./generalTheming/cursor.nix
    ./generalTheming/gtk.nix
    ./generalTheming/qt.nix
    ./system/generalConfig.nix
    ./system/xdgConfig.nix
  ];
}
