{...}:
{
  imports =
  [
    ./customOptions/desktopOptions.nix
    ./hardware/amdgpu.nix
    ./hardware/amdvlk.nix
    ./hardware/bluetooth.nix
    ./hardware/kernel.nix
    ./hardware/printing.nix
    ./hardware/sound.nix
    ./software/flatpak.nix
    ./software/fileManager.nix
    ./software/gaming.nix
    ./software/generalSoftware.nix
    ./software/virtualisation.nix
    ./software/terminal.nix
    ./system/defaultEnvVar.nix
    ./system/defaultServices.nix
    ./system/fonts.nix
    ./system/security.nix
  ];
}
