{...}:
{
  imports =
  [
    ./customOptions/desktopDriverOptions.nix
    ./customOptions/desktopSoftwareOptions.nix
    ./customOptions/desktopSystemOptions.nix
    ./hardware/amdgpu.nix
    ./hardware/kernel.nix
    ./hardware/printing.nix
    ./hardware/sound.nix
    ./software/flatpak.nix
    ./software/fileManager.nix
    ./software/gaming.nix
    ./software/generalSoftware.nix
    ./software/virtualisation.nix
    ./software/terminal.nix
    ./system/defaultEnvVar.nix
    ./system/commonOptions.nix
    ./system/fonts.nix
    ./system/security.nix
  ];
}
